version: "3"
volumes:
  lemurweb:
services:
  lemur-web:
    image: regentmarkets/lemur-web
    networks:
      platform:
        aliases:
          - web
    volumes:
      - lemurweb:/usr/local/src/lemur/lemur/static/dist
    environment:
      DEBUG: 'False'
      LEMUR_CONF: /usr/local/src/lemur/lemur.conf.py
  lemur-nginx:
    image: regentmarkets/lemur-nginx
    networks:
      platform:
        aliases:
          - nginx
    ports:
      - 4430:443
    volumes:
      - lemurweb:/usr/local/src/lemur/lemur/static/dist

  postgres:
    image: postgres:latest
    networks:
      platform:
        aliases:
          - postgres
    ports:
      - "5432:5432"

networks:
  platform:
